import uuid
import enum
from sqlalchemy import Column, String, DateTime, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from app.db.session import Base

class CampaignStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class Campaign(Base):
    __tablename__ = "campaigns"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    campaign_name = Column(String, index=True, nullable=False)
    status = Column(SQLEnum(CampaignStatus), default=CampaignStatus.PENDING, nullable=False)
    target_geo = Column(String, nullable=True)
    target_niches = Column(JSONB, default=list)  # List of strings e.g. ["Dental", "Barbershop"]
    ai_config = Column(JSONB, default=dict)       # Config generated by AI Strategist
    stats = Column(JSONB, default=dict)           # Scraped, enriched, duplicates stats
    error_log = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
